### ISSUE TITLE
Give Pelias team access to this repo

### ISSUE THREAD

**Issue by orangejulius** [geopipes/geonames-stream#12]
We're going to want to change this repo eventually, since the Pelias Geonames importer depends on it. What's the best way to do that?

Move it to the pelias org?
Add pelias team members to the geopipes org?
Move this into pelias/geonames itself?

**Comment by riordan** [comment]
Are there any downstream users of geopipes who'd be affected if we moved it into Pelias? I suspect anyone else using it would be installing via NPM.

**Comment by orangejulius** [comment]
Done!
