### ISSUE TITLE
Unexpected "Use Only Once" paradigm

### ISSUE THREAD

**Issue by royaltm** [geopipes/geonames-stream#9]
```js
var geonames = require('geonames-stream'),
    request = require('request'), 
    split = require('split');

function test(url, callback) {
  var count = 0;
  request.get( url ).
    pipe(geonames.unzip()).
    pipe(split()).
    pipe(geonames.parser()).
    pipe(geonames.modifiers()).
    on('end', function(){
      callback(count);
    }).
    on('data',function(d){ ++count });
}

test('http://download.geonames.org/export/dump/NZ.zip', function(count) {
  console.log("end NZ: " + count);
  test('http://download.geonames.org/export/dump/PL.zip', console.log);
});

```

```
end NZ: 67551

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write after end
```

didn't actually get to the bottom of this yet, but my wild guess is that the issue is [here](https://github.com/geopipes/geonames-stream/blob/master/lib/unzip.js#L5)

**Comment by missinglink** [comment]
My suspicion is that one of the streams being returned for either `geonames.unzip()`, `geonames.parser()` or `geonames.modifiers()` is a singleton (in that calling the same function twice returns the same stream)

At the end of your first `test()` the `end` event is being emitted on each stream in the pipeline which results in the error `write after end` when trying to re-use that closed pipe on the second `test()`

cc/ @sevko

**Comment by royaltm** [comment]
The pass-thgrough `output` should be initialized every time you call unzip(). My pull-requests fixes it just fine.

**Comment by missinglink** [comment]
Thanks @royaltm, your changes are now available via `npm`.

```bash
$ npm publish
npm http PUT https://registry.npmjs.org/geonames-stream
npm http 201 https://registry.npmjs.org/geonames-stream
+ geonames-stream@2.0.3
```
